name: Crea los archivos del modelo

on:
  [workflow_dispatch]

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Alistar los archivos archivos del modelo de clasificaci√≥n
        uses: actions/checkout@v2