name: Prepara el contenedor del modelo

on:
  [workflow_dispatch]

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Gesti√≥n de la Imagen para el contenedor
        uses: actions/checkout@v4
      - name: Crea la imagen
        run: docker build ./${{ vars.PROJECT_NAME }} -t docker.io/${{ vars.DOCKER_ACCT }}/${{ vars.IMG_CANONICAL }}:${{ vars.IMG_VER }}
      - name: Registra la Imagen en Docker-Hub
        run: |
          docker login -u ${{ vars.DOCKER_ACCT }} -p ${{secrets.DOCKER_KEY}}
          docker push docker.io/${{ vars.DOCKER_ACCT }}/${{ vars.IMG_CANONICAL }}:${{ vars.IMG_VER }}
          docker tag docker.io/${{ vars.DOCKER_ACCT }}/${{ vars.IMG_CANONICAL }}:${{ vars.IMG_VER }} ${{ vars.GCP_ZONE }}-docker.pkg.dev/${{ vars.GCP_PROJECT_LAB }}/${{ vars.GCP_IMG_REPO }}/${{ vars.IMG_CANONICAL }}:${{ vars.IMG_VER }}
