name: Prepara el contenedor del modelo

on:
  [workflow_dispatch]

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Gestión de la Imagen para el contenedor
        uses: actions/checkout@v4
      - name: Crea la imagen
        run: docker build ./${{ vars.PROJECT_NAME }} -t docker.io/${{ vars.DOCKER_ACCT }}/${{ vars.IMG_CANONICAL }}:${{ vars.IMG_VER }}
      #- name: Registra la Imagen en Docker-Hub
      #  run: |
      #    docker login -u a01794620 -p dckr_pat_Xoh1nA75rqJF4MqAPUjxkM9VJdw
      #    docker push docker.io/a01794620/mlops_e57:latest
      #    docker tag docker.io/a01794620mlops_e57:latest us-central1-docker.pkg.dev/laboratorio1-447417/mlflow-mlops-g57/mlops_e57:latest

#- name: Autentica en GCP vía IAM
#id: auth
#uses: google-github-actions/auth@v2
#with:
#credentials_json: '${{secrets.GCP_CREDS}}'
#- name: Prepara el ambiente de consola en GCP
#uses: google-github-actions/setup-gcloud@v2
#- name: Publica la Imagen en el Artifact Registry en GCP
#run: gcloud auth configure-docker ${{ vars.GCP_ZONE }}-docker.pkg.dev
#- name: Registra la Imagen al Artifact Registry en GCP desde el Docker-Hub
#run: docker push ${{ vars.GCP_ZONE }}-docker.pkg.dev/${{ vars.GCP_PROJECT_LAB }}/${{ vars.GCP_IMG_REPO }}/${{ vars.GCP_IMG_CANNONICAL }}:${{ vars.GCP_IMG_VER }}