name: Prepara el contenedor del modelo

on:
  [workflow_dispatch]

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Gesti√≥n de la Imagen para el contenedor
        uses: actions/checkout@v4
      - name: Crea la imagen
        run: docker build ./${{ vars.PROJECT_NAME }} -t docker.io/${{ vars.DOCKER_ACCT }}/${{ vars.IMG_CANONICAL }}:${{ vars.IMG_VER }}
        